wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n
  central_auth_host: https://meta.wikimedia.org
  maintenance_notice:
    date: 2019-03-12 @ 1500 UTC
    url: https://meta.wikimedia.org/wiki/Wiki_labels/Downtime_20190312

wsgi:
  host: labels.wmflabs.org
  application_root: ""
  url_prefix: ""
  scheme: 'https'
  cors_allowed: https://([^\.\/]+\.)?(wiki([pm]edia|data|books|versity|quote|source|news|voyage)|wiktionary|mediawiki)\.org

database:
  host: localhost
  dbname: wikilabels

oauth:
  mw_uri: https://meta.wikimedia.org/w/index.php
  creds: oauth-wikimedia.yaml
